
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://afhjvlnptaxfletfmxnr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFmaGp2bG5wdGF4ZmxldGZteG5yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5ODE5MDIsImV4cCI6MjA1NzU1NzkwMn0.KUjX0e5BDGUPI2EsVoPni31IRiHih-mohN1oe7a7Umo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
